site_name: spectrocube
repo_url: https://github.com/queezz/spectrocube
strict: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy
nav:
  - Home: index.md
  - Specification: spec.md
  - Usage: usage.md
  - API Reference: reference.md
extra_css:
  - stylesheets/extra.css
